---
name: Tensorflow.js
menu: Tensorflow
---

# Tensorflow.js

## Problem Solving Process

1. Identify data relevant to problem (features, labels)
2. Assemble a set of data related to problem to be solved
3. Decide on the type of output you are predicting
4. Based on type of output, pick an algorithm that will determine a correlation between your 'features' and 'labels'
5. use model generated by algorithm to make a prediction

## Continuous vs Discrete

We can decide what application or technique we are going to used based on the type of output.

For example, if the output data itself is continuous, we know that we would apply regression. If in fact the output data is discrete in nature ie pass/fail, then we would consider options like classification.

## Plinko Example

In the example of Plinko, we want to try figure out where a ball dropped into the Plinko grid will end up.

From the example, we can determine that we have these features:

1. Drop Position
2. Ball Bounciness
3. Ball Size

From these pieces of data, we want to know the output label of which bucket a ball lands in.
