#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run gen:folderIndex

if [ -n "$(git status --porcelain)" ]; then
	# There are changes
	git add --all
	git commit -m "chore: updated folder index files" --no-verify
	echo "\n[Husky] Committed changes to folder index files. You will need to push new changes."
else
	echo "\nNo changes from gen:folderIndex. Exiting."
fi
